python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF001
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF002
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF003
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF004
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF005
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF006
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF007
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF008
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF009
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF010
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF011
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF012
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF013
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF014
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF015
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF016
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF017
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF018
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF019
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF020
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF021
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF022
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF023
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF024
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF025
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF026
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF027
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF028
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF029
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF030
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF031
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF032
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF033
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF034
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF035
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF036
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF037
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF038
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF039
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF040
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF041
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF042
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF043
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF044
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF045
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF046
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF047
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF048
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF049
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF050
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF051
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF052
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF053
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF054
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF055
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF056
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF057
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF058
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF059
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF060
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF061
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF062
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF063
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF064
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF065
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF066
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF067
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF068
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF069
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF070
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF071
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF072
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF073
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF074
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF075
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF076
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF077
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF078
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF079
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF080
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF081
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF082
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF083
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF084
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF085
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF086
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF087
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF088
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF089
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF090
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF091
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF092
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF093
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF094
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF095
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF096
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF097
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF098
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF099
python bpt_training.py --model TTLep_PDF --feature_plots --version v3 --nTraining -1 --debug --variation PDF100
