#python bpt_training.py --model TTLep_JERC --feature_plots --nTraining -1 --debug
# systematics = ["hf", "lf",  "cferr1", "cferr2", "lfstats1", "lfstats2", "hfstats1", "hfstats2"]

mprof run "python bpt_training.py --model TTLep_bTagSys --version v3 --overwrite training --feature_plots --nTraining -1 --debug --variation hf"; mprof plot --output=mem.pdf; scp mem.pdf schoef@lxplus.cern.ch:/eos/home-s/schoef/www/tmp/TTLep_bTagSys_hf.pdf
mprof run "python bpt_training.py --model TTLep_bTagSys --version v3 --overwrite training --feature_plots --nTraining -1 --debug --variation lf"; mprof plot --output=mem.pdf; scp mem.pdf schoef@lxplus.cern.ch:/eos/home-s/schoef/www/tmp/TTLep_bTagSys_lf.pdf
mprof run "python bpt_training.py --model TTLep_bTagSys --version v3 --overwrite training --feature_plots --nTraining -1 --debug --variation cferr1"; mprof plot --output=mem.pdf; scp mem.pdf schoef@lxplus.cern.ch:/eos/home-s/schoef/www/tmp/TTLep_bTagSys_cferr1.pdf
mprof run "python bpt_training.py --model TTLep_bTagSys --version v3 --overwrite training --feature_plots --nTraining -1 --debug --variation cferr2"; mprof plot --output=mem.pdf; scp mem.pdf schoef@lxplus.cern.ch:/eos/home-s/schoef/www/tmp/TTLep_bTagSys_cferr2.pdf
mprof run "python bpt_training.py --model TTLep_bTagSys --version v3 --overwrite training --feature_plots --nTraining -1 --debug --variation lfstats1"; mprof plot --output=mem.pdf; scp mem.pdf schoef@lxplus.cern.ch:/eos/home-s/schoef/www/tmp/TTLep_bTagSys_lfstats1.pdf
mprof run "python bpt_training.py --model TTLep_bTagSys --version v3 --overwrite training --feature_plots --nTraining -1 --debug --variation lfstats2"; mprof plot --output=mem.pdf; scp mem.pdf schoef@lxplus.cern.ch:/eos/home-s/schoef/www/tmp/TTLep_bTagSys_lfstats2.pdf
mprof run "python bpt_training.py --model TTLep_bTagSys --version v3 --overwrite training --feature_plots --nTraining -1 --debug --variation hfstats1"; mprof plot --output=mem.pdf; scp mem.pdf schoef@lxplus.cern.ch:/eos/home-s/schoef/www/tmp/TTLep_bTagSys_hfstats1.pdf
mprof run "python bpt_training.py --model TTLep_bTagSys --version v3 --overwrite training --feature_plots --nTraining -1 --debug --variation hfstats2"; mprof plot --output=mem.pdf; scp mem.pdf schoef@lxplus.cern.ch:/eos/home-s/schoef/www/tmp/TTLep_bTagSys_hfstats2.pdf
