python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --feature_plots --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --lepton_kinematics --asymmetry --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score --top_kinematics --lepton_kinematics --asymmetry                   
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score --top_kinematics --lepton_kinematics             --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score --top_kinematics --lepton_kinematics                               
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score --top_kinematics                     --asymmetry --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score --top_kinematics                     --asymmetry                   
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score --top_kinematics                                 --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score --top_kinematics                                                   
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                  --lepton_kinematics --asymmetry --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                  --lepton_kinematics --asymmetry                   
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                  --lepton_kinematics             --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                  --lepton_kinematics                               
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                                      --asymmetry --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                                      --asymmetry                   
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                                                  --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                                                                    
python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes --prefix v1.1 --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score #SPLIT100 

#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --feature_plots --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --lepton_kinematics --asymmetry --spin_correlation
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score --top_kinematics --lepton_kinematics --asymmetry                   
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score --top_kinematics --lepton_kinematics             --spin_correlation
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score --top_kinematics --lepton_kinematics                               
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score --top_kinematics                     --asymmetry --spin_correlation
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score --top_kinematics                     --asymmetry                   
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score --top_kinematics                                 --spin_correlation
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score --top_kinematics                                                   
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                  --lepton_kinematics --asymmetry --spin_correlation
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                  --lepton_kinematics --asymmetry                   
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                  --lepton_kinematics             --spin_correlation
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                  --lepton_kinematics                               
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                                      --asymmetry --spin_correlation
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                                      --asymmetry                   
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                                                  --spin_correlation
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score                                                                    
#python  multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --coefficients ctGRe ctj8 ctj1 ctu1 cQd8 --loss CrossEntropy --debug --n_trees 300                 --learn_global_score #SPLIT100 

#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias --feature_plots --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation --bias tr_ttbar_pt "10**(({})/600)"
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1 --feature_plots --coefficients ctGRe ctGIm cQj18 cQj38 ctj8 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation 


#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  ctGRe --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation 
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  ctGIm --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation 
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  cQj18 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  cQj38 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  cQj11 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  cQj31 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  ctu8 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  ctd8 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  ctj8 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  cQu8 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  cQd8 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  ctu1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  ctj1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  cQu1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation
#python   multi_bit_training.py --plot_directory multiBIT_TT2l_EFT_delphes --model TT2l_EFT_delphes_red --prefix v1.1_bias_pT --bias tr_ttbar_pt "10**(({})/600)" --coefficients  cQd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --asymmetry --spin_correlation
#
