python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --lepton_kinematics --asymmetry --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --lepton_kinematics --asymmetry                   
python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --lepton_kinematics             --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics --lepton_kinematics                               
python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics                     --asymmetry --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics                     --asymmetry                   
python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics                                 --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score --top_kinematics                                                   
python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score                  --lepton_kinematics --asymmetry --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score                  --lepton_kinematics --asymmetry                   
python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score                  --lepton_kinematics             --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score                  --lepton_kinematics                               
python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score                                      --asymmetry --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score                                      --asymmetry                   
python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score                                                  --spin_correlation
python  multi_bit_training.py --plot_directory multiBIT_TT2lUnbinned --prefix v1 --coefficients ctGRe cQj11 ctu8 ctj8 ctu1 ctd1 --loss CrossEntropy --debug --n_trees 300 --learn_global_score                                                                    
