# without bkg
# TTTT
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTTT_MS --EFTCoefficients ctt   --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTTT_MS --EFTCoefficients cQt1  --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTTT_MS --EFTCoefficients cQt8  --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTTT_MS --EFTCoefficients cQQ1  --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTTT_MS --EFTCoefficients cQQ8  --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTTT_MS --EFTCoefficients ctHRe --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTTT_MS --EFTCoefficients ctHIm --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
# TTbb
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients ctt      --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQt1     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQt8     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQQ1     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQQ8     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients ctHRe    --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients ctHIm    --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients ctb1     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients ctb8     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQb1     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQb8     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQtQb1Re --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQtQb1Im --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQtQb8Re --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
python3 2l_MVA_EFT.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQtQb8Im --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.0001 --ReLU_slope 0.5  #
#
# with bkg
# TTTT
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTTT_MS --EFTCoefficients ctt   --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTTT_MS --EFTCoefficients cQt1  --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTTT_MS --EFTCoefficients cQt8  --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTTT_MS --EFTCoefficients cQQ1  --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTTT_MS --EFTCoefficients cQQ8  --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTTT_MS --EFTCoefficients ctHRe --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --n_epochs 2000 --lr 0.1 --sample TTTT_MS --EFTCoefficients ctHIm --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
# TTbb                
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --input_directory /eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v7/MVA-training/ttbb_2l_dilep2-bjet_delphes-njet4p-btag1p/ --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients ctt      --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --input_directory /eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v7/MVA-training/ttbb_2l_dilep2-bjet_delphes-njet4p-btag1p/ --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQt1     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --input_directory /eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v7/MVA-training/ttbb_2l_dilep2-bjet_delphes-njet4p-btag1p/ --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQt8     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --input_directory /eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v7/MVA-training/ttbb_2l_dilep2-bjet_delphes-njet4p-btag1p/ --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQQ1     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --input_directory /eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v7/MVA-training/ttbb_2l_dilep2-bjet_delphes-njet4p-btag1p/ --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQQ8     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --input_directory /eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v7/MVA-training/ttbb_2l_dilep2-bjet_delphes-njet4p-btag1p/ --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients ctHRe    --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --input_directory /eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v7/MVA-training/ttbb_2l_dilep2-bjet_delphes-njet4p-btag1p/ --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients ctHIm    --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --input_directory /eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v7/MVA-training/ttbb_2l_dilep2-bjet_delphes-njet4p-btag1p/ --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients ctb1     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --input_directory /eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v7/MVA-training/ttbb_2l_dilep2-bjet_delphes-njet4p-btag1p/ --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients ctb8     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --input_directory /eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v7/MVA-training/ttbb_2l_dilep2-bjet_delphes-njet4p-btag1p/ --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQb1     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --input_directory /eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v7/MVA-training/ttbb_2l_dilep2-bjet_delphes-njet4p-btag1p/ --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQb8     --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --input_directory /eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v7/MVA-training/ttbb_2l_dilep2-bjet_delphes-njet4p-btag1p/ --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQtQb1Re --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --input_directory /eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v7/MVA-training/ttbb_2l_dilep2-bjet_delphes-njet4p-btag1p/ --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQtQb1Im --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --input_directory /eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v7/MVA-training/ttbb_2l_dilep2-bjet_delphes-njet4p-btag1p/ --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQtQb8Re --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
python3 2l_MVA_EFT+bkg.py --plot_directory /groups/hephy/cms/lena.wild/www/tttt/plots/DNN+bkg_allops_v2 --input_directory /eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v7/MVA-training/ttbb_2l_dilep2-bjet_delphes-njet4p-btag1p/ --n_epochs 2000 --lr 0.1 --sample TTbb_MS --EFTCoefficients cQtQb8Im --animate --animate_step 100 --animate_fps 4 --dropout 0.5 --scheduler linear+flat 0.001 --add_bkg --ReLU_slope 0.5  #
