from math import pi

tex = {"ctGIm":"C_{tG}^{Im}", "ctGRe":"C_{tG}^{Re}", "cQj18":"c_{Qj}^{18}" ,"cQj38":"c_{Qj}^{38}" ,"cQj11":"c_{Qj}^{11}" ,"cjj31":"c_{jj}^{31}" ,"ctu8":"c_{tu}^{8}" ,"ctd8":"c_{td}^{8}" ,"ctj8":"c_{tj}^{8}" ,"cQu8":"c_{Qu}^{8}" ,"cQd8":"c_{Qd}^{8}" ,"ctu1":"c_{tu}^{1}" ,"ctd1":"c_{td}^{1}" ,"ctj1":"c_{tj}^{1}" ,"cQu1":"c_{Qu}^{1}" ,"cQd1":"c_{Qd}^{1}"}

plot_options =  {


    "parton_top1_decayAngle_theta" :{'binning':[30,0,pi], 'tex':'#theta(t_{1})'},
    "parton_top1_decayAngle_phi"   :{'binning':[30,-pi,pi], 'tex':'#phi(t_{1})'},
    "parton_top1_pt" :{'binning':[50,0,1500], 'tex':'p_{T}(t_{1})'},
    "parton_top1_eta" :{'binning':[30,-3,3], 'tex':'#eta(t_{1})'},
    "parton_top1_f1_pt" :{'binning':[30,0,800], 'tex':'p_{T}(f_{1}(t_{1}))'},
    "parton_top1_f1_eta" :{'binning':[30,-3,3], 'tex':'#eta(f_{2}(t_{1}))'},
    "parton_top1_f2_pt" :{'binning':[30,0,800], 'tex':'p_{T}(f_{2} (t_{1}))'},
    "parton_top1_f2_eta" :{'binning':[30,-3,3], 'tex':'#eta(f_{2}(t_{1}))'},
    "parton_top1_b_pt" :{'binning':[50,0,800], 'tex':'p_{T}(b (t_{1}))'},
    "parton_top1_b_eta" :{'binning':[30,-3,3], 'tex':'#eta(b(t_{1}))'},
    "parton_top1_W_pt" :{'binning':[30,0,1000], 'tex':'p_{T}(W (t_{1}))'},
    "parton_top1_W_eta" :{'binning':[30,-3,3], 'tex':'#eta(W(t_{1}))'},

    "parton_top2_decayAngle_theta" :{'binning':[30,0,pi], 'tex':'#theta(t_{2})'},
    "parton_top2_decayAngle_phi"   :{'binning':[30,-pi,pi], 'tex':'#phi(t_{2})'},
    "parton_top2_pt" :{'binning':[50,0,1500], 'tex':'p_{T}(t_{2})'},
    "parton_top2_eta" :{'binning':[30,-3,3], 'tex':'#eta(t_{2})'},
    "parton_top2_f1_pt" :{'binning':[30,0,800], 'tex':'p_{T}(f_{1}(t_{2}))'},
    "parton_top2_f1_eta" :{'binning':[30,-3,3], 'tex':'#eta(f_{1}(t_{2}))'},
    "parton_top2_f2_pt" :{'binning':[30,0,800], 'tex':'p_{T}(f_{2} (t_{2}))'},
    "parton_top2_f2_eta" :{'binning':[30,-3,3], 'tex':'#eta(f_{2}(t_{2}))'},
    "parton_top2_b_pt" :{'binning':[50,0,800], 'tex':'p_{T}(b (t_{2}))'},
    "parton_top2_b_eta" :{'binning':[30,-3,3], 'tex':'#eta(b(t_{2}))'},
    "parton_top2_W_pt" :{'binning':[30,0,1000], 'tex':'p_{T}(W (t_{2}))'},
    "parton_top2_W_eta" :{'binning':[30,-3,3], 'tex':'#eta(W(t_{2}))'},

    "parton_top12_pt":{'binning':[50,0,1000], 'tex':'p_{T}(t#bar{t})'},
    "parton_top12_mass":{'binning':[50,0,2000], 'tex':'M(t#bar{t})'},
    "parton_top12_eta":{'binning':[30,-3,3], 'tex':'#eta(t#bar{t})'},
    "parton_top12_dEta":{'binning':[30,-3,3], 'tex':'#Delta#eta(t#bar{t})'},
    "parton_top12_dAbsEta":{'binning':[30,-3,3], 'tex':'#Delta|#eta|(t#bar{t})'},

    "parton_cosThetaPlus_n"     :{'binning':[30,-1,1], 'tex':'cos#theta^{+}_{n}'},
    "parton_cosThetaMinus_n"    :{'binning':[30,-1,1], 'tex':'cos#theta^{-}_{n}'},
    "parton_cosThetaPlus_r"     :{'binning':[30,-1,1], 'tex':'cos#theta^{+}_{r}'},
    "parton_cosThetaMinus_r"    :{'binning':[30,-1,1], 'tex':'cos#theta^{-}_{r}'},
    "parton_cosThetaPlus_k"     :{'binning':[30,-1,1], 'tex':'cos#theta^{+}_{k}'},
    "parton_cosThetaMinus_k"    :{'binning':[30,-1,1], 'tex':'cos#theta^{-}_{k}'},
    "parton_cosThetaPlus_r_star"    :{'binning':[30,-1,1], 'tex':'cos#theta^{+*}_{n}'},
    "parton_cosThetaMinus_r_star"   :{'binning':[30,-1,1], 'tex':'cos#theta^{-*}_{n}'},
    "parton_cosThetaPlus_k_star"    :{'binning':[30,-1,1], 'tex':'cos#theta^{+*}_{k}'},
    "parton_cosThetaMinus_k_star"   :{'binning':[30,-1,1], 'tex':'cos#theta^{-*}_{k}'},
    "parton_xi_nn"              :{'binning':[30,-1,1], 'tex':'#xi_{nn}'},
    "parton_xi_rr"              :{'binning':[30,-1,1], 'tex':'#xi_{rr}'},
    "parton_xi_kk"              :{'binning':[30,-1,1], 'tex':'#xi_{kk}'},
    "parton_xi_nr_plus"         :{'binning':[30,-1,1], 'tex':'#xi_{nr}^{+}'},
    "parton_xi_nr_minus"        :{'binning':[30,-1,1], 'tex':'#xi_{nr}^{-}'},
    "parton_xi_rk_plus"         :{'binning':[30,-1,1], 'tex':'#xi_{rk}^{+}'},
    "parton_xi_rk_minus"        :{'binning':[30,-1,1], 'tex':'#xi_{rk}^{-}'},
    "parton_xi_nk_plus"         :{'binning':[30,-1,1], 'tex':'#xi_{nk}^{+}'},
    "parton_xi_nk_minus"        :{'binning':[30,-1,1], 'tex':'#xi_{nk}^{-}'},

    "parton_xi_r_star_k"        :{'binning':[30,-1,1], 'tex':'#xi_{r^{*}k}'},
    "parton_xi_k_r_star"        :{'binning':[30,-1,1], 'tex':'#xi_{kr^{*}}'},
    "parton_xi_kk_star"         :{'binning':[30,-1,1], 'tex':'#xi_{kk^{*}}'},

    "parton_cos_phi"            :{'binning':[30,-1,1], 'tex':'cos(#phi)'},
    "parton_cos_phi_lab"        :{'binning':[30,-1,1], 'tex':'cos(#phi lab)'},
    "parton_abs_delta_phi_ll_lab":{'binning':[30,0,pi], 'tex':'|#Delta(#phi(l,l))|'},

    "recoBj01_pt"     :{'binning':[30,0,1500], 'tex':'p_{T}(bb)'},
    "recoBj01_mass"   :{'binning':[30,0,1500], 'tex':'M(bb)'},
    "nBTag"           :{'binning':[4,0,4], 'tex':'N_{b}'},
    "recoLep0_pt"     :{'binning':[21,20,220], 'tex':'p_{T}(l_{1})'},
    "recoLep0_eta"   :{'binning':[26,-2.6,2.6], 'tex':'#eta(l_{1})'},
    "recoLep1_pt"   :{'binning':[21,20,220], 'tex':'p_{T}(l_{2})'},
    "recoLep1_eta"   :{'binning':[26,-2.6,2.6], 'tex':'#eta(l_{2})'},
    "recoLepPos_pt"   :{'binning':[21,20,220], 'tex':'p_{T}(l^{+})'},
    "recoLepPos_eta"   :{'binning':[26,-2.6,2.6], 'tex':'#eta(l^{+})'},
    "recoLepNeg_pt"   :{'binning':[21,20,220], 'tex':'p_{T}(l^{-})'},
    "recoLepNeg_eta"   :{'binning':[26,-2.6,2.6], 'tex':'#eta(l^{-})'},
    "recoLep01_pt"   :{'binning':[21,0,220], 'tex':'p_{T}(ll)'},
    "recoLep01_mass"   :{'binning':[20,20,520], 'tex':'M(ll)'},
    "recoLep_dPhi"     :{'binning':[30,-pi,pi], 'tex':'#Delta#phi(ll)'},
    "recoLep_dEta"     :{'binning':[26,-2.6,2.6], 'tex':'#Delta#eta(ll)'},
    "recoLep_dAbsEta"     :{'binning':[26,-2.6,2.6], 'tex':'#Delta|#eta|(ll)'},

    "tr_top_decayAngle_theta" :{'binning':[30,0,pi], 'tex':'#theta(t_{1})'},
    "tr_top_decayAngle_phi"   :{'binning':[30,-pi,pi], 'tex':'#phi(t_{1})'},
    "tr_top_pt" :{'binning':[20,0,800], 'tex':'p_{T}(t_{1})'},
    "tr_top_eta" :{'binning':[26,-2.6,2.6], 'tex':'#eta(t_{1})'},
    "tr_top_f1_pt" :{'binning':[30,0,800], 'tex':'p_{T}(f_{1}(t_{1}))'},
    "tr_top_f1_eta" :{'binning':[30,-3,3], 'tex':'#eta(f_{2}(t_{1}))'},
    "tr_top_f2_pt" :{'binning':[30,0,800], 'tex':'p_{T}(f_{2} (t_{1}))'},
    "tr_top_f2_eta" :{'binning':[30,-3,3], 'tex':'#eta(f_{2}(t_{1}))'},
    "tr_top_b_pt" :{'binning':[50,0,800], 'tex':'p_{T}(b (t_{1}))'},
    "tr_top_b_eta" :{'binning':[30,-3,3], 'tex':'#eta(b(t_{1}))'},
    "tr_top_W_pt" :{'binning':[30,0,1000], 'tex':'p_{T}(W (t_{1}))'},
    "tr_top_W_eta" :{'binning':[30,-3,3], 'tex':'#eta(W(t_{1}))'},

    "tr_topBar_decayAngle_theta" :{'binning':[30,0,pi], 'tex':'#theta(t_{2})'},
    "tr_topBar_decayAngle_phi"   :{'binning':[30,-pi,pi], 'tex':'#phi(t_{2})'},
    "tr_topBar_pt" :{'binning':[20,0,800], 'tex':'p_{T}(t_{2})'},
    "tr_topBar_eta" :{'binning':[26,-2.6,2.6], 'tex':'#eta(t_{2})'},
    "tr_topBar_f1_pt" :{'binning':[30,0,800], 'tex':'p_{T}(f_{1}(t_{2}))'},
    "tr_topBar_f1_eta" :{'binning':[30,-3,3], 'tex':'#eta(f_{1}(t_{2}))'},
    "tr_topBar_f2_pt" :{'binning':[30,0,800], 'tex':'p_{T}(f_{2} (t_{2}))'},
    "tr_topBar_f2_eta" :{'binning':[30,-3,3], 'tex':'#eta(f_{2}(t_{2}))'},
    "tr_topBar_b_pt" :{'binning':[50,0,800], 'tex':'p_{T}(b (t_{2}))'},
    "tr_topBar_b_eta" :{'binning':[30,-3,3], 'tex':'#eta(b(t_{2}))'},
    "tr_topBar_W_pt" :{'binning':[30,0,1000], 'tex':'p_{T}(W (t_{2}))'},
    "tr_topBar_W_eta" :{'binning':[30,-3,3], 'tex':'#eta(W(t_{2}))'},

    "tr_ttbar_pt":{'binning':[20,0,500], 'tex':'p_{T}(t#bar{t})'},
    "tr_ttbar_mass":{'binning':[20,750,1750], 'tex':'M(t#bar{t})'},
    "tr_ttbar_eta":{'binning':[26,-2.6,2.6], 'tex':'#eta(t#bar{t})'},
    "tr_ttbar_dEta":{'binning':[26,-2.6,2.6], 'tex':'#Delta#eta(t#bar{t})'},
    "tr_ttbar_dAbsEta":{'binning':[26,-2.6,2.6], 'tex':'#Delta|#eta|(t#bar{t})'},

    "tr_cosThetaPlus_n"     :{'binning':[30,-1,1], 'tex':'cos#theta^{+}_{n}'},
    "tr_cosThetaMinus_n"    :{'binning':[30,-1,1], 'tex':'cos#theta^{-}_{n}'},
    "tr_cosThetaPlus_r"     :{'binning':[30,-1,1], 'tex':'cos#theta^{+}_{r}'},
    "tr_cosThetaMinus_r"    :{'binning':[30,-1,1], 'tex':'cos#theta^{-}_{r}'},
    "tr_cosThetaPlus_k"     :{'binning':[30,-1,1], 'tex':'cos#theta^{+}_{k}'},
    "tr_cosThetaMinus_k"    :{'binning':[30,-1,1], 'tex':'cos#theta^{-}_{k}'},
    "tr_cosThetaPlus_r_star"    :{'binning':[30,-1,1], 'tex':'cos#theta^{+*}_{n}'},
    "tr_cosThetaMinus_r_star"   :{'binning':[30,-1,1], 'tex':'cos#theta^{-*}_{n}'},
    "tr_cosThetaPlus_k_star"    :{'binning':[30,-1,1], 'tex':'cos#theta^{+*}_{k}'},
    "tr_cosThetaMinus_k_star"   :{'binning':[30,-1,1], 'tex':'cos#theta^{-*}_{k}'},
    "tr_xi_nn"              :{'binning':[30,-1,1], 'tex':'#xi_{nn}'},
    "tr_xi_rr"              :{'binning':[30,-1,1], 'tex':'#xi_{rr}'},
    "tr_xi_kk"              :{'binning':[30,-1,1], 'tex':'#xi_{kk}'},
    "tr_xi_nr_plus"         :{'binning':[30,-1,1], 'tex':'#xi_{nr}^{+}'},
    "tr_xi_nr_minus"        :{'binning':[30,-1,1], 'tex':'#xi_{nr}^{-}'},
    "tr_xi_rk_plus"         :{'binning':[30,-1,1], 'tex':'#xi_{rk}^{+}'},
    "tr_xi_rk_minus"        :{'binning':[30,-1,1], 'tex':'#xi_{rk}^{-}'},
    "tr_xi_nk_plus"         :{'binning':[30,-1,1], 'tex':'#xi_{nk}^{+}'},
    "tr_xi_nk_minus"        :{'binning':[30,-1,1], 'tex':'#xi_{nk}^{-}'},

    "tr_xi_r_star_k"        :{'binning':[30,-1,1], 'tex':'#xi_{r^{*}k}'},
    "tr_xi_k_r_star"        :{'binning':[30,-1,1], 'tex':'#xi_{kr^{*}}'},
    "tr_xi_kk_star"         :{'binning':[30,-1,1], 'tex':'#xi_{kk^{*}}'},

    "tr_cos_phi"            :{'binning':[30,-1,1], 'tex':'cos(#phi)'},
    "tr_cos_phi_lab"        :{'binning':[30,-1,1], 'tex':'cos(#phi lab)'},
    "tr_abs_delta_phi_ll_lab":{'binning':[30,0,pi], 'tex':'|#Delta(#phi(l,l))|'},


    "nrecoJet":{'binning':[7,3,10], 'tex':'N_{jet}'},
    "nrecoLep":{'binning':[4,0,4], 'tex':'N_{lep}'},
    "jet0_pt":{'binning':[30,0,800], 'tex':'p_{T}(jet0)'},
    "jet1_pt":{'binning':[30,0,800], 'tex':'p_{T}(jet1)'},
    "ht":{'binning':[30,0,1500], 'tex':'H_T'},

    "Generator_x1":{'binning':[30,0,1], 'tex':'x_{1,Bjorken}'},
    "Generator_x2":{'binning':[30,0,1], 'tex':'x_{2,Bjorken}'},
    "Generator_id1":{'binning':[26,-5,21], 'tex':'PDGID(1)'},
    "Generator_id2":{'binning':[26,-5,21], 'tex':'PDGID(2)'},

}

