python  bpt_training.py --version v7 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTotal              
python  bpt_training.py --version v7 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalPileUp     
python  bpt_training.py --version v7 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalRelative   
python  bpt_training.py --version v7 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalAbsolute   
python  bpt_training.py --version v7 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalPt         
python  bpt_training.py --version v7 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalScale      
python  bpt_training.py --version v7 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalMC         
python  bpt_training.py --version v7 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTotalNoFlavor      
python  bpt_training.py --version v7 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTotalNoTime        
python  bpt_training.py --version v7 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTotalNoFlavorNoTime
python  bpt_training.py --version v7 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTimePtEta          

python  bpt_training.py --version v7 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTotal              
python  bpt_training.py --version v7 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalPileUp     
python  bpt_training.py --version v7 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalRelative   
python  bpt_training.py --version v7 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalAbsolute   
python  bpt_training.py --version v7 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalPt         
python  bpt_training.py --version v7 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalScale      
python  bpt_training.py --version v7 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalMC         
python  bpt_training.py --version v7 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTotalNoFlavor      
python  bpt_training.py --version v7 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTotalNoTime        
python  bpt_training.py --version v7 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTotalNoFlavorNoTime
python  bpt_training.py --version v7 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTimePtEta          

python  bpt_training.py --version v7 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTotal              
python  bpt_training.py --version v7 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalPileUp     
python  bpt_training.py --version v7 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalRelative   
python  bpt_training.py --version v7 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalAbsolute   
python  bpt_training.py --version v7 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalPt         
python  bpt_training.py --version v7 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalScale      
python  bpt_training.py --version v7 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSubTotalMC         
python  bpt_training.py --version v7 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTotalNoFlavor      
python  bpt_training.py --version v7 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTotalNoTime        
python  bpt_training.py --version v7 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTotalNoFlavorNoTime
python  bpt_training.py --version v7 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTimePtEta          
