python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTotal
python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesAbsoluteMPFBias
python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesAbsoluteScale
python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesAbsoluteStat
python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesRelativeBal
python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesRelativeFSR
python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesRelativePtBB
python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesRelativeStatFSR
python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesPileUpDataMC
python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesPileUpPtBB
python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesPileUpPtRef
python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesFlavorQCD
python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesFragmentation
python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSinglePionECAL
python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSinglePionHCAL
python  bpt_training.py --version v4.1 --model TTLep_JERC_ptt_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTimePtEta

#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTotal
#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesAbsoluteMPFBias
#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesAbsoluteScale
#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesAbsoluteStat
#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesRelativeBal
#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesRelativeFSR
#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesRelativePtBB
#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesRelativeStatFSR
#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesPileUpDataMC
#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesPileUpPtBB
#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesPileUpPtRef
#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesFlavorQCD
#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesFragmentation
#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSinglePionECAL
#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSinglePionHCAL
#python  bpt_training.py --version v4.1 --model TTLep_JERC_NJet_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTimePtEta
#
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTotal
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesAbsoluteMPFBias
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesAbsoluteScale
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesAbsoluteStat
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesRelativeBal
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesRelativeFSR
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesRelativePtBB
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesRelativeStatFSR
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesPileUpDataMC
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesPileUpPtBB
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesPileUpPtRef
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesFlavorQCD
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesFragmentation
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSinglePionECAL
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesSinglePionHCAL
#python  bpt_training.py --version v4.1 --model TTLep_JERC_linear_paper --modelDir models --feature_plots --nTraining -1 --debug --variation jesTimePtEta
#
