branches =[   "genJet_pt", "genJet_nConstituents",
                    "genJet_SDmass", "genJet_SDsubjet0_deltaEta", "genJet_SDsubjet0_deltaPhi", "genJet_SDsubjet0_deltaR",
                    "genJet_SDsubjet0_mass", "genJet_SDsubjet1_deltaEta", "genJet_SDsubjet1_deltaPhi",
                    "genJet_SDsubjet1_deltaR", "genJet_SDsubjet1_mass",
                    "genJet_tau1", "genJet_tau2", "genJet_tau3", "genJet_tau4", "genJet_tau21", "genJet_tau32", 
                    "genJet_ecf1", "genJet_ecf2", "genJet_ecf3", "genJet_ecfC1", "genJet_ecfC2", "genJet_ecfC3",
                    "genJet_ecfD", "genJet_ecfDbeta2", "genJet_ecfM1", "genJet_ecfM2", "genJet_ecfM3", "genJet_ecfM1beta2",
                    "genJet_ecfM2beta2", "genJet_ecfM3beta2", "genJet_ecfN1", "genJet_ecfN2", "genJet_ecfN3", "genJet_ecfN1beta2",
                    "genJet_ecfN2beta2", "genJet_ecfN3beta2", "genJet_ecfU1", "genJet_ecfU2", "genJet_ecfU3", "genJet_ecfU1beta2",
                    "genJet_ecfU2beta2", "genJet_ecfU3beta2",
                    # "genJet_mass",
                    ]
branches1 = [
           # 'target_ctWRe',
           # 'target_ctBRe',
           # 'target_cHQ3',
           # 'target_cHt',
           # 'target_cHtbRe',
           # 'target_ctWIm',
           # 'target_ctBIm',
           # 'target_cHtbIm',
           # 'target_ctWRe_ctWRe',
           # 'target_ctWRe_ctBRe',
           # 'target_ctWRe_cHQ3',
           # 'target_ctWRe_cHt',
           # 'target_ctWRe_cHtbRe',
           # 'target_ctWRe_ctWIm',
           # 'target_ctWRe_ctBIm',
           # 'target_ctWRe_cHtbIm',
           # 'target_ctBRe_ctBRe',
           # 'target_ctBRe_cHQ3',
           # 'target_ctBRe_cHt',
           # 'target_ctBRe_cHtbRe',
           # 'target_ctBRe_ctWIm',
           # 'target_ctBRe_ctBIm',
           # 'target_ctBRe_cHtbIm',
           # 'target_cHQ3_cHQ3',
           # 'target_cHQ3_cHt',
           # 'target_cHQ3_cHtbRe',
           # 'target_cHQ3_ctWIm',
           # 'target_cHQ3_ctBIm',
           # 'target_cHQ3_cHtbIm',
           # 'target_cHt_cHt',
           # 'target_cHt_cHtbRe',
           # 'target_cHt_ctWIm',
           # 'target_cHt_ctBIm',
           # 'target_cHt_cHtbIm',
           # 'target_cHtbRe_cHtbRe',
           # 'target_cHtbRe_ctWIm',
           # 'target_cHtbRe_ctBIm',
           # 'target_cHtbRe_cHtbIm',
           # 'target_ctWIm_ctWIm',
           # 'target_ctWIm_ctBIm',
           # 'target_ctWIm_cHtbIm',
           # 'target_ctBIm_ctBIm',
           # 'target_ctBIm_cHtbIm',
           # 'target_cHtbIm_cHtbIm',
           # 'run',
           # 'lumi',
           # 'evt',
           # 'rw_nominal',
           # 'ref_lumiweight1fb',
            # 'partonTop_pt',
            # 'partonTop_eta',
           # 'partonTop_phi',
            # 'partonTop_mass',
           # 'partonTop_pdgId',
            'genQ1_pt',
            'genQ1_eta',
           # 'genQ1_phi',
            # 'genQ1_mass',
           # 'genQ1_pdgId',
            'genQ2_pt',
            'genQ2_eta',
           # 'genQ2_phi',
            # 'genQ2_mass',
           # 'genQ2_pdgId',
            'genb_pt',
            'genb_eta',
            # 'genb_phi',
            # 'genb_mass',
           # 'genb_pdgId',
            'genW_pt',
            'genW_eta',
           # 'genW_phi',
            # 'genW_mass',
            # 'genTop_pt',
            # 'genTop_eta',
           # 'genTop_phi',
            # 'genTop_mass',
            'gen_theta',
           # 'gen_phi',
            'genJet_pt',
            'genJet_eta',
           # 'genJet_phi',
           # 'genJet_mass',
           # 'genJet_nConstituents',
           # 'genJet_isMuon',
           # 'genJet_isElectron',
           # 'genJet_isPhoton',
           'genJet_SDmass',
           'genJet_SDsubjet0_eta',
           'genJet_SDsubjet0_deltaEta',
           # 'genJet_SDsubjet0_phi',
           # 'genJet_SDsubjet0_deltaPhi',
           # 'genJet_SDsubjet0_deltaR',
           'genJet_SDsubjet0_mass',
           'genJet_SDsubjet1_eta',
           'genJet_SDsubjet1_deltaEta',
           # 'genJet_SDsubjet1_phi',
           # 'genJet_SDsubjet1_deltaPhi',
           # 'genJet_SDsubjet1_deltaR',
           'genJet_SDsubjet1_mass',
           # 'genJet_tau1',
           # 'genJet_tau2',
           # 'genJet_tau3',
           # 'genJet_tau4',
            'genJet_tau21',
            'genJet_tau32',
           'genJet_ecf1',
           'genJet_ecf2',
           'genJet_ecf3',
           'genJet_ecfC1',
           'genJet_ecfC2',
           'genJet_ecfC3',
           'genJet_ecfD',
           # 'genJet_ecfDbeta2',
           # 'genJet_ecfM1',
           # 'genJet_ecfM2',
           # 'genJet_ecfM3',
           # 'genJet_ecfM1beta2',
           # 'genJet_ecfM2beta2',
           # 'genJet_ecfM3beta2',
           # 'genJet_ecfN1',
           # 'genJet_ecfN2',
           # 'genJet_ecfN3',
           # 'genJet_ecfN1beta2',
           # 'genJet_ecfN2beta2',
           # 'genJet_ecfN3beta2',
           # 'genJet_ecfU1',
           # 'genJet_ecfU2',
           # 'genJet_ecfU3',
           # 'genJet_ecfU1beta2',
           # 'genJet_ecfU2beta2',
           # 'genJet_ecfU3beta2',
           # 'dR_genJet_Q1',
           # 'dR_genJet_Q2',
           # 'dR_genJet_W',
           # 'dR_genJet_b',
           # 'dR_genJet_top',
           # 'dR_genJet_maxQ1Q2b',
           # 'label_lin_0',
           # 'label_lin_1',
           # 'label_lin_2',
           # 'label_lin_3',
           # 'label_quad_0',
           # 'label_quad_1',
           # 'label_quad_2',
           # 'label_quad_3',
           # 'gen_cand_sum_pt',
            # 'ne',
            # 'e_pt',
           # 'e_etarel',
           # 'e_phirel',
           # 'e_eta',
           # 'e_phi',
           # 'e_pdgId',
           # 'e_charge',
            # 'nmu',
            # 'mu_pt',
           # 'mu_etarel',
           # 'mu_phirel',
           # 'mu_eta',
           # 'mu_phi',
           # 'mu_pdgId',
           # 'mu_charge',
            # 'nph',
            # 'ph_pt',
           # 'ph_etarel',
           # 'ph_phirel',
           # 'ph_eta',
           # 'ph_phi',
           # 'ph_pdgId',
            # 'nchh',
            # 'chh_pt',
           # 'chh_etarel',
           # 'chh_phirel',
           # 'chh_eta',
           # 'chh_phi',
           # 'chh_pdgId',
           # 'chh_charge',
            # 'nneh',
            'neh_pt',
           # 'neh_etarel',
           # 'neh_phirel',
           # 'neh_eta',
           # 'neh_phi',
           # 'neh_pdgId',
           # 'nweight',
           # 'weight_base',
           # 'np',
            # 'p_C',
           # 'chi2_ndof'
           ]
