python asimov.py --prefit --linear --bit_name multiBit_TT2lUnbinned_TK_False_LK_False_CA_False_SC_False_v1_coeffs_ctGRe_ctGIm_cQj18_cQj38_ctj8_nTraining_-1_nTrees_300 --wc1 cQj38 --wc2 ctj8
python asimov.py --prefit --linear --bit_name multiBit_TT2lUnbinned_TK_False_LK_False_CA_False_SC_True_v1_coeffs_ctGRe_ctGIm_cQj18_cQj38_ctj8_nTraining_-1_nTrees_300 --wc1 cQj38 --wc2 ctj8
python asimov.py --prefit --linear --bit_name multiBit_TT2lUnbinned_TK_False_LK_False_CA_True_SC_False_v1_coeffs_ctGRe_ctGIm_cQj18_cQj38_ctj8_nTraining_-1_nTrees_300 --wc1 cQj38 --wc2 ctj8
python asimov.py --prefit --linear --bit_name multiBit_TT2lUnbinned_TK_False_LK_False_CA_True_SC_True_v1_coeffs_ctGRe_ctGIm_cQj18_cQj38_ctj8_nTraining_-1_nTrees_300 --wc1 cQj38 --wc2 ctj8
python asimov.py --prefit --linear --bit_name multiBit_TT2lUnbinned_TK_False_LK_True_CA_False_SC_False_v1_coeffs_ctGRe_ctGIm_cQj18_cQj38_ctj8_nTraining_-1_nTrees_300 --wc1 cQj38 --wc2 ctj8
python asimov.py --prefit --linear --bit_name multiBit_TT2lUnbinned_TK_False_LK_True_CA_False_SC_True_v1_coeffs_ctGRe_ctGIm_cQj18_cQj38_ctj8_nTraining_-1_nTrees_300 --wc1 cQj38 --wc2 ctj8
python asimov.py --prefit --linear --bit_name multiBit_TT2lUnbinned_TK_False_LK_True_CA_True_SC_False_v1_coeffs_ctGRe_ctGIm_cQj18_cQj38_ctj8_nTraining_-1_nTrees_300 --wc1 cQj38 --wc2 ctj8
python asimov.py --prefit --linear --bit_name multiBit_TT2lUnbinned_TK_False_LK_True_CA_True_SC_True_v1_coeffs_ctGRe_ctGIm_cQj18_cQj38_ctj8_nTraining_-1_nTrees_300 --wc1 cQj38 --wc2 ctj8
python asimov.py --prefit --linear --bit_name multiBit_TT2lUnbinned_TK_True_LK_False_CA_False_SC_False_v1_coeffs_ctGRe_ctGIm_cQj18_cQj38_ctj8_nTraining_-1_nTrees_300 --wc1 cQj38 --wc2 ctj8
python asimov.py --prefit --linear --bit_name multiBit_TT2lUnbinned_TK_True_LK_False_CA_False_SC_True_v1_coeffs_ctGRe_ctGIm_cQj18_cQj38_ctj8_nTraining_-1_nTrees_300 --wc1 cQj38 --wc2 ctj8
python asimov.py --prefit --linear --bit_name multiBit_TT2lUnbinned_TK_True_LK_False_CA_True_SC_False_v1_coeffs_ctGRe_ctGIm_cQj18_cQj38_ctj8_nTraining_-1_nTrees_300 --wc1 cQj38 --wc2 ctj8
python asimov.py --prefit --linear --bit_name multiBit_TT2lUnbinned_TK_True_LK_False_CA_True_SC_True_v1_coeffs_ctGRe_ctGIm_cQj18_cQj38_ctj8_nTraining_-1_nTrees_300 --wc1 cQj38 --wc2 ctj8
python asimov.py --prefit --linear --bit_name multiBit_TT2lUnbinned_TK_True_LK_True_CA_False_SC_False_v1_coeffs_ctGRe_ctGIm_cQj18_cQj38_ctj8_nTraining_-1_nTrees_300 --wc1 cQj38 --wc2 ctj8
python asimov.py --prefit --linear --bit_name multiBit_TT2lUnbinned_TK_True_LK_True_CA_False_SC_True_v1_coeffs_ctGRe_ctGIm_cQj18_cQj38_ctj8_nTraining_-1_nTrees_300 --wc1 cQj38 --wc2 ctj8
python asimov.py --prefit --linear --bit_name multiBit_TT2lUnbinned_TK_True_LK_True_CA_True_SC_False_v1_coeffs_ctGRe_ctGIm_cQj18_cQj38_ctj8_nTraining_-1_nTrees_300 --wc1 cQj38 --wc2 ctj8
